#prefix for the ingress name
ingressPrefix: <prefix>
ingress:
  #Domain name of the ingress controller in the cluster namespace
  host: <ingress-host>
  #annotations for the ingress object
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60" 
# The application URLs will be in the format of <PROTOCOL>://<ingressprefix>.<ingress host>/<APPLICATION PATH>
# Ex: if the value of prefix is 'prod' and ingress-host value is 'docu.cfcr-lab.bp-paas.otxlab.net' 
# then to access ACS application, the URL will be some thing like http://prod.docu.cfcr-lab.bp-paas.otxlab.net/ACS/servlet/ACS

jmsService:
  enable: false
  serviceName: <jms-service-name> 
  servicePort: 9080

jmsBase:
  enable: false
  serviceName: <jms-service-name> 
  servicePort: 9080

acsService:
  enable: true
  serviceName: <jms-service-name> 
  servicePort: 9080
  
tnsService:
  enable: false
  serviceName: <tns-service-name>
  servicePort: 8081

d2clientService:
  enable: false
  serviceName: <d2client-service-name>
  servicePort: 8080

d2configService:
  enable: true
  serviceName: <d2config-service-name>
  servicePort: 8080

daService:
  enable: false
  serviceName: <da-service-name>
  servicePort: 8080

appHostService:
  enable: false
  serviceName: <apphost-service-name> 
  servicePort: 8080

bamService:
  enable: false
  serviceName: <bam-service-name>
  servicePort: 8080

bpsService:
  enable: false
  serviceName: <bps-service-name>
  servicePort: 8080

xdaService:
  enable: false
  serviceName: <xda-service-name>
  servicePort: 7000

dsearchadminService:
  enable: false
  serviceName: <dsearchadmin-service-name>
  servicePort: 9300

indexagentService:
  enable: false
  serviceName: <indexagent-service-name>
  servicePort: 9200

dfsService:
  enable: false
  serviceName: <dfs-service-name>
  servicePort: 8080
